"""refactor inventory models

Revision ID: b9f6bfb37c63
Revises: b206cf93c3ca
Create Date: 2025-01-03 17:02:59.023471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f6bfb37c63'
down_revision: Union[str, None] = 'b206cf93c3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('threshold', sa.Float(), nullable=False))
    op.drop_column('inventory', 'quantity_used')
    op.add_column('material', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('material', sa.Column('cost_per_unit', sa.Float(), nullable=False))
    op.drop_column('material', 'unit_cost')
    op.drop_column('material', 'unit_of_measure')
    op.drop_column('material_assignment', 'quantity_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_assignment', sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('unit_of_measure', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('material', 'cost_per_unit')
    op.drop_column('material', 'unit')
    op.add_column('inventory', sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('inventory', 'threshold')
    op.drop_column('activity', 'duration')
    # ### end Alembic commands ###
